/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class AdminMenuGUI extends javax.swing.JFrame {
    private User user;

    public AdminMenuGUI(User user) {
        this.user = user;
        initComponents();
        jLabelTitle.setText("Hello, "+user.getUserId()); 
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String currentTime = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                lblTime.setText("Current Time: " + currentTime);
                }
            });
        timer.start();
        String fullText = "   Welcome to AUTOMATED PURCHASE ORDER MANAGEMENT SYSTEM      ";
        StringBuilder marqueeText = new StringBuilder(fullText);

        Timer marqueeTimer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  
                   char first = marqueeText.charAt(0);
                   marqueeText.deleteCharAt(0).append(first);
                   lblMarquee.setText(marqueeText.toString());
               }
           });
           marqueeTimer.start();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        smbtn = new javax.swing.JButton();
        pmbtn = new javax.swing.JButton();
        imbtn = new javax.swing.JButton();
        fmbtn = new javax.swing.JButton();
        btnUserRegistration = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblMarquee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("Welcome User");

        smbtn.setText("Sales Manager Page");
        smbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smbtnActionPerformed(evt);
            }
        });

        pmbtn.setText("Purchase Manager Page");
        pmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmbtnActionPerformed(evt);
            }
        });

        imbtn.setText("Inventory Manager Page");
        imbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imbtnActionPerformed(evt);
            }
        });

        fmbtn.setText("Finance Manager Page");
        fmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmbtnActionPerformed(evt);
            }
        });

        btnUserRegistration.setText("User Registration");
        btnUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegistrationActionPerformed(evt);
            }
        });

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setText("Time");

        lblMarquee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMarquee.setText("Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(189, 189, 189)
                .addComponent(btnLogout)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fmbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(smbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pmbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUserRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblMarquee))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblTime)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblMarquee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserRegistration)
                .addGap(18, 18, 18)
                .addComponent(smbtn)
                .addGap(18, 18, 18)
                .addComponent(pmbtn)
                .addGap(18, 18, 18)
                .addComponent(imbtn)
                .addGap(18, 18, 18)
                .addComponent(fmbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smbtnActionPerformed
        SalesManagerMenuGUI salesmanager = new SalesManagerMenuGUI(this.user);
        salesmanager.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_smbtnActionPerformed

    private void btnUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegistrationActionPerformed
        AdminUserGUI createuser = new AdminUserGUI(this.user);
        createuser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserRegistrationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to Logout?", "Confirm Logout?",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            OWSBLoginGUI loginForm = new OWSBLoginGUI();
            loginForm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void fmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmbtnActionPerformed
        FinanceManagerMenuGUI financemanager = new FinanceManagerMenuGUI(this.user);
        financemanager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fmbtnActionPerformed

    private void pmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmbtnActionPerformed
        PurchaseManagerMenuGUI purchasemanager = new PurchaseManagerMenuGUI(this.user);
        purchasemanager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pmbtnActionPerformed

    private void imbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imbtnActionPerformed
        InventoryManagerMenuGUI inventorymanager = new InventoryManagerMenuGUI(this.user);
        inventorymanager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imbtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserRegistration;
    private javax.swing.JButton fmbtn;
    private javax.swing.JButton imbtn;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel lblMarquee;
    private javax.swing.JLabel lblTime;
    private javax.swing.JButton pmbtn;
    private javax.swing.JButton smbtn;
    // End of variables declaration//GEN-END:variables
}
