/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

public class FinanceManagerMenuGUI extends javax.swing.JFrame {

    private User user;
    
  
    public FinanceManagerMenuGUI(User user) {
        this.user = user;
        initComponents();
        lblUserid.setText("Hello, "+user.getUserId());  
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String currentTime = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                lblTime.setText("Current Time: " + currentTime);
                }
            });
        timer.start();
        String fullText = "   Welcome to AUTOMATED PURCHASE ORDER MANAGEMENT SYSTEM      ";
        StringBuilder marqueeText = new StringBuilder(fullText);

        Timer marqueeTimer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  
                   char first = marqueeText.charAt(0);
                   marqueeText.deleteCharAt(0).append(first);
                   lblMarquee.setText(marqueeText.toString());
               }
           });
           marqueeTimer.start();       
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserid = new javax.swing.JLabel();
        btnVerifyPurchaseOrder = new javax.swing.JButton();
        btnVerifyInventoryUpdate = new javax.swing.JButton();
        btnGenerateFinancialReport = new javax.swing.JButton();
        btnViewPurchaseRequisition = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnUpdateBudget = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblMarquee = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUserid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnVerifyPurchaseOrder.setText("Verify Purchase Order");
        btnVerifyPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyPurchaseOrderActionPerformed(evt);
            }
        });

        btnVerifyInventoryUpdate.setText("Verify Inventory Updates");
        btnVerifyInventoryUpdate.setMaximumSize(new java.awt.Dimension(144, 23));
        btnVerifyInventoryUpdate.setMinimumSize(new java.awt.Dimension(144, 23));
        btnVerifyInventoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyInventoryUpdateActionPerformed(evt);
            }
        });

        btnGenerateFinancialReport.setText("Generate Financial Reports");
        btnGenerateFinancialReport.setMaximumSize(new java.awt.Dimension(144, 23));
        btnGenerateFinancialReport.setMinimumSize(new java.awt.Dimension(144, 23));
        btnGenerateFinancialReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateFinancialReportActionPerformed(evt);
            }
        });

        btnViewPurchaseRequisition.setText("View Purchase Requisitions");
        btnViewPurchaseRequisition.setMaximumSize(new java.awt.Dimension(144, 23));
        btnViewPurchaseRequisition.setMinimumSize(new java.awt.Dimension(144, 23));
        btnViewPurchaseRequisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPurchaseRequisitionActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnUpdateBudget.setText("Update Budget");
        btnUpdateBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBudgetActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMarquee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMarquee.setText("Welcome to ");

        jToggleButton1.setText("View Supplier Performace Report");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblTime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblMarquee)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerifyPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerifyInventoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateFinancialReport, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPurchaseRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(lblUserid)
                            .addGap(175, 175, 175)
                            .addComponent(btnLogOut)
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addGap(240, 240, 240)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserid))
                .addGap(18, 18, 18)
                .addComponent(lblMarquee)
                .addGap(9, 9, 9)
                .addComponent(btnVerifyPurchaseOrder)
                .addGap(18, 18, 18)
                .addComponent(btnVerifyInventoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateBudget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateFinancialReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnViewPurchaseRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            OWSBLoginGUI loginWindow = new OWSBLoginGUI();
            loginWindow.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnGenerateFinancialReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateFinancialReportActionPerformed
         
        FMFinancialReportGUI reportgui = new FMFinancialReportGUI(this.user);
        reportgui.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGenerateFinancialReportActionPerformed

    private void btnVerifyPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyPurchaseOrderActionPerformed
        FMVerifyPurchaseOrderGUI vpogui = new FMVerifyPurchaseOrderGUI(this.user);
        vpogui.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnVerifyPurchaseOrderActionPerformed

    private void btnViewPurchaseRequisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPurchaseRequisitionActionPerformed
        
        FMViewPurchaseRequisitionsGUI viewPR = new FMViewPurchaseRequisitionsGUI(this.user);
        viewPR.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewPurchaseRequisitionActionPerformed

    private void btnVerifyInventoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyInventoryUpdateActionPerformed
         
        FMVerifyInventoryGUI verify = new FMVerifyInventoryGUI(this.user);
        verify.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVerifyInventoryUpdateActionPerformed

    private void btnUpdateBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBudgetActionPerformed
        FMBudgetUpdateGUI gui = new FMBudgetUpdateGUI(this.user);
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUpdateBudgetActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        FMSupplierPerformanceReportGUI gui = new FMSupplierPerformanceReportGUI(this.user);
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateFinancialReport;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdateBudget;
    private javax.swing.JButton btnVerifyInventoryUpdate;
    private javax.swing.JButton btnVerifyPurchaseOrder;
    private javax.swing.JButton btnViewPurchaseRequisition;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblMarquee;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserid;
    // End of variables declaration//GEN-END:variables
}
