/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FMFinancialReportGUI extends javax.swing.JFrame {
    private User user;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"PO Id", "Supplier Id", "Item Name",
        "Item Id", "Total Amount", "Status"};
    

    public FMFinancialReportGUI(User user) {
        this.user = user;
        initComponents();
        model.setColumnIdentifiers(columnName);
        loadFinancialReport();
    }

    private void loadFinancialReport() {
        List<PurchaseOrder> orders = FileHandler.readPurchaseOrders();
        
        ReportGenerator report = new FMFinanceReport(orders, tableFinancialReport, lblPaid, lblUnpaid);
        report.generateReport();
        
        
        FMBudgetManager budgetManager = new FMBudgetManager();
        String currentMonth = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM"));

        Budget currentBudget = budgetManager.getBudgetByMonth(currentMonth);

        double monthlyBudget = 0;
        if (currentBudget != null) {
            monthlyBudget = currentBudget.getAmount(); //  Extract double from Budget
        } else {
            JOptionPane.showMessageDialog(this, "No budget found for " + currentMonth,
                "Missing Budget", JOptionPane.ERROR_MESSAGE);
        }

        
        double totalPaid = budgetManager.getTotalPaidThisMonth(orders, currentMonth);
        double remaining = monthlyBudget - totalPaid;

        lblBudget.setText("RM " + String.format("%.2f", monthlyBudget));
        lblRemaining.setText("RM " + String.format("%.2f", remaining));

        if (remaining < 0) {
            lblStatus.setText("Over Budget");
            lblStatus.setForeground(Color.RED);
        } else if (remaining < monthlyBudget * 0.2) {
            lblStatus.setText("Nearing Limit");
            lblStatus.setForeground(Color.ORANGE);
        } else {
            lblStatus.setText("Within Budget");
            lblStatus.setForeground(new Color(0, 128, 0)); // dark green
        }
        
}
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFinancialReport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblPaid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUnpaid = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Financial Report");

        tableFinancialReport.setModel(model);
        jScrollPane1.setViewportView(tableFinancialReport);

        jLabel2.setText("Total Paid:");

        lblPaid.setText("RM");

        jLabel4.setText("Total Unpaid Orders:");

        lblUnpaid.setText("jLabel5");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Monthly Budget:");

        jLabel5.setText("Remaining Budget:");

        jLabel6.setText("Budget Usage Status:");

        lblBudget.setText("jLabel7");

        lblRemaining.setText("jLabel8");

        lblStatus.setText("jLabel9");

        btnCSV.setText("Export to CSV");
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCSV)
                                    .addGap(146, 146, 146)
                                    .addComponent(btnBack)
                                    .addGap(67, 67, 67))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRemaining)
                                        .addComponent(lblStatus))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUnpaid)
                                .addComponent(lblPaid)
                                .addComponent(lblBudget))
                            .addGap(380, 380, 380)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPaid))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnpaid)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblRemaining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCSV))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FinanceManagerMenuGUI Window = new FinanceManagerMenuGUI(this.user);
        Window.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save CSV Report");
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".csv")) {
                filePath += ".csv";
            }
            FMFinanceReport.exportTableToCSV(tableFinancialReport, filePath);
        }
    }//GEN-LAST:event_btnCSVActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblPaid;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUnpaid;
    private javax.swing.JTable tableFinancialReport;
    // End of variables declaration//GEN-END:variables
}
