/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;


import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;


public class FMVerifyInventoryGUI extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"POId", "PRId", "ItemId", "ItemName", "Quantity", "SupplierId", 
        "UnitPrice", "TotalAmount", "PurchaseManager", "Status", "ReceivedQty", "Finance Flag"};
    private ButtonGroup filterGroup = new ButtonGroup();
    private User user;
    
    public FMVerifyInventoryGUI(User user) {
        this.user = user;
        initComponents();
        filterGroup.add(defaultRadio);
        filterGroup.add(verifiedRadio);
        filterGroup.add(paidRadio);
        model.setColumnIdentifiers(columnName);
        defaultRadio.setSelected(true);
        loadData();
    }
    
    private void loadData() {
        FMVerifyInventory loader = new FMVerifyInventory(model); 
        loader.loadTable(); 
        
    }
    private void loadVerifiedData() {    
        FMVerifyInventory loader = new FMVerifyInventory(model);
        loader.loadOnlyReceivedOrders();
       
    }
    
    private void processPayment() {
        int selectedRow = tableInvUpdate.getSelectedRow();
        FMVerifyInventory logic = new FMVerifyInventory(model);
        logic.processPayment(selectedRow, tableInvUpdate); 
    }
    private void loadPaidData() {
        FMVerifyInventory loader = new FMVerifyInventory(model);
        loader.loadPaidData();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableInvUpdate = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnProcessPayment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        defaultRadio = new javax.swing.JRadioButton();
        verifiedRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        paidRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableInvUpdate.setModel(model);
        jScrollPane1.setViewportView(tableInvUpdate);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnProcessPayment.setText("Process Payment to Supplier");
        btnProcessPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessPaymentActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        defaultRadio.setText("Default");

        verifiedRadio.setText("Verified List");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Verify inventory updates from the Inventory Manager");

        paidRadio.setText("Paid List");
        paidRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(defaultRadio)
                .addGap(53, 53, 53)
                .addComponent(verifiedRadio)
                .addGap(29, 29, 29)
                .addComponent(paidRadio)
                .addGap(35, 35, 35)
                .addComponent(btnRefresh)
                .addGap(264, 264, 264))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 327, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnProcessPayment)
                                .addGap(351, 351, 351)
                                .addComponent(btnBack)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(244, 244, 244))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(defaultRadio)
                    .addComponent(verifiedRadio)
                    .addComponent(paidRadio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessPayment)
                    .addComponent(btnBack))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FinanceManagerMenuGUI Window = new FinanceManagerMenuGUI(this.user);
        Window.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        if (defaultRadio.isSelected()) {
            loadData(); // show all POs
        }
        if (verifiedRadio.isSelected()) {
            loadVerifiedData(); // show only 'Received'
        }    
        if (paidRadio.isSelected()) {
            loadPaidData(); // show only 'Paid'
        }
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnProcessPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPaymentActionPerformed
        processPayment();
    }//GEN-LAST:event_btnProcessPaymentActionPerformed

    private void paidRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidRadioActionPerformed
        
    }//GEN-LAST:event_paidRadioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcessPayment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JRadioButton defaultRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton paidRadio;
    private javax.swing.JTable tableInvUpdate;
    private javax.swing.JRadioButton verifiedRadio;
    // End of variables declaration//GEN-END:variables
}
