/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;

import java.awt.Dimension;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IMGenerateStockReportGUI extends javax.swing.JFrame {
    private User user;

    public IMGenerateStockReportGUI(User user) {
        this.user = user;
        initComponents();
        lblReportOwner.setText(user.getUserId()); 
        this.setPreferredSize(new Dimension(720, 450));
        this.pack();
        this.setLocationRelativeTo(null);
        
        DefaultTableModel model = new DefaultTableModel(
            new Object[][] {},
            new String[] { "Item ID", "Item Name", "Supplier ID", "Quantity", "Low-Stock Alert" }
        ) {
            Class[] types = new Class[] {
                String.class, String.class, String.class, Integer.class, Boolean.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        tableStockReportItems.setModel(model); 
        tableStockReportItems.getTableHeader().setReorderingAllowed(false);
        
        lblReportType.setText("Stock Report");
        lblReportDate.setText(java.time.LocalDate.now().toString());
        
        List<IMStockReport> existingStockReports = FileHandler.loadExistingStockReports();
        IMGenerateStockReport logic = new IMGenerateStockReport(model);
        String reportID = logic.getNextReportID(existingStockReports);

        lblReportID.setText(reportID);

        IMGenerateStockReport tableLoader = new IMGenerateStockReport(model);
        tableLoader.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblReportDate = new javax.swing.JLabel();
        lblReportTypeIndicator = new javax.swing.JLabel();
        lblReportOwnerIndicator = new javax.swing.JLabel();
        lblDateIndicator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStockReportItems = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        lblReportIDIndicator = new javax.swing.JLabel();
        lblReportID = new javax.swing.JLabel();
        lblReportType = new javax.swing.JLabel();
        lblReportOwner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPageName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageName.setText("Generate Stock Report");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblReportDate.setText("ReportDate");

        lblReportTypeIndicator.setText("Report Type    :");

        lblReportOwnerIndicator.setText("Generated by  :");

        lblDateIndicator.setText("Generated on  :");

        tableStockReportItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Supplier ID", "Quantity", "Low-Stock Alert"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableStockReportItems);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblReportIDIndicator.setText("Report ID        :");

        lblReportID.setText("ReportID");

        lblReportType.setText("ReportType");

        lblReportOwner.setText("ReportOwner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(597, 597, 597)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDateIndicator)
                            .addComponent(lblReportOwnerIndicator)
                            .addComponent(lblReportTypeIndicator)
                            .addComponent(lblReportIDIndicator))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReportType)
                            .addComponent(lblReportOwner)
                            .addComponent(lblReportID)
                            .addComponent(lblReportDate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPageName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportIDIndicator)
                    .addComponent(lblReportID))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportTypeIndicator)
                    .addComponent(lblReportType))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportOwnerIndicator)
                    .addComponent(lblReportOwner))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateIndicator)
                    .addComponent(lblReportDate))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(3, 3, 3)
                .addComponent(btnBack))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        InventoryManagerMenuGUI mainPage = new InventoryManagerMenuGUI(this.user);
        mainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String reportID = lblReportID.getText();
        String reportType = lblReportType.getText();
        String reportOwner = lblReportOwner.getText();
        String reportDate = lblReportDate.getText();

        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to save this stock report?", 
            "Confirm Save", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tableStockReportItems.getModel();
            List<Item> items = new ArrayList<>();

            for (int i = 0; i < model.getRowCount(); i++) {
                String itemID = model.getValueAt(i, 0).toString();
                String itemName = model.getValueAt(i, 1).toString();
                String supplierID = model.getValueAt(i, 2).toString();
                int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());
                boolean isLowStock = Boolean.parseBoolean(model.getValueAt(i, 4).toString());
                String status = isLowStock ? "Low-Stock" : "Normal";

                Item item = new Item(itemID, itemName, supplierID, quantity, 0.0, reportDate, status); 
                items.add(item);
            }

            IMGenerateStockReport logic = new IMGenerateStockReport(model);
            logic.saveStockReport(reportID, reportType, reportOwner, reportDate, items);

            JOptionPane.showMessageDialog(this, "Report saved as " + reportID + ".csv");
            btnSave.setVisible(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateIndicator;
    private javax.swing.JLabel lblPageName;
    private javax.swing.JLabel lblReportDate;
    private javax.swing.JLabel lblReportID;
    private javax.swing.JLabel lblReportIDIndicator;
    private javax.swing.JLabel lblReportOwner;
    private javax.swing.JLabel lblReportOwnerIndicator;
    private javax.swing.JLabel lblReportType;
    private javax.swing.JLabel lblReportTypeIndicator;
    private javax.swing.JTable tableStockReportItems;
    // End of variables declaration//GEN-END:variables
}
