/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IMManageStockLevelsGUI extends javax.swing.JFrame {
    private User user;

    public IMManageStockLevelsGUI(User user) {
        this.user = user;
        initComponents();
        this.setPreferredSize(new Dimension(720, 450));
        this.pack();
        this.setLocationRelativeTo(null);
        
        btnConfirm.setVisible(false);
        btnReset.setVisible(false);

        DefaultTableModel model = new DefaultTableModel(
            new Object[][] {},
            new String[] { "Item ID", "Item Name", "Supplier ID", "Quantity", "Low-Stock Alert" }
        ) {
            Class[] types = new Class[] {
                String.class, String.class, String.class, Integer.class, Boolean.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3; 
            }
        };

        tableStockItems.setModel(model); 
        tableStockItems.getTableHeader().setReorderingAllowed(false);
        model.addTableModelListener(e -> {
            if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                btnConfirm.setVisible(true);
                btnReset.setVisible(true);
            }
        });
        IMManageStockLevels tableLoader = new IMManageStockLevels(model);
        tableLoader.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStockItems = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPageName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageName.setText("Manage Stock Levels");

        tableStockItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Supplier ID", "Quantity", "Low-Stock Alert"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableStockItems);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPageName)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addComponent(btnConfirm))
                .addGap(6, 6, 6)
                .addComponent(btnBack))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        InventoryManagerMenuGUI mainPage = new InventoryManagerMenuGUI(this.user);
        mainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to reset all received quantities?", 
        "Confirm Reset", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        DefaultTableModel model = (DefaultTableModel) tableStockItems.getModel();
        IMManageStockLevels tableLoader = new IMManageStockLevels(model);
        tableLoader.loadTable();

        btnConfirm.setVisible(false);
        btnReset.setVisible(false);
    }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableStockItems.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());
            if (quantity < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Quantity cannot be negative.",
                    "Invalid Input", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);

                IMManageStockLevels loader = new IMManageStockLevels(model);
                loader.loadTable();
                btnConfirm.setVisible(false);
                btnReset.setVisible(false);
                return;
            }
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to update stock levels?",
            "Confirm Update",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            IMManageStockLevels manager = new IMManageStockLevels(model);
            manager.updateStockItems();
            manager.loadTable();

            javax.swing.JOptionPane.showMessageDialog(this, "Stock levels updated successfully.");
            btnConfirm.setVisible(false);
            btnReset.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPageName;
    private javax.swing.JTable tableStockItems;
    // End of variables declaration//GEN-END:variables
}
