/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class InventoryManagerMenuGUI extends javax.swing.JFrame {
    private User user;

    public InventoryManagerMenuGUI(User user) {
        this.user = user;
        initComponents();
        lblWelcome.setText("Hello, "+user.getUserId()); 
        this.setPreferredSize(new Dimension(720, 450));
        this.pack();
        this.setLocationRelativeTo(null);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String currentTime = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                lblTime.setText("Current Time: " + currentTime);
                }
            });
        timer.start();
        String fullText = "   Welcome to AUTOMATED PURCHASE ORDER MANAGEMENT SYSTEM      ";
        StringBuilder marqueeText = new StringBuilder(fullText);

        Timer marqueeTimer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  
                   char first = marqueeText.charAt(0);
                   marqueeText.deleteCharAt(0).append(first);
                   lblMarquee.setText(marqueeText.toString());
               }
           });
           marqueeTimer.start();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnViewItemList = new javax.swing.JButton();
        btnManageStockLevels = new javax.swing.JButton();
        btnViewPurchaseOrder = new javax.swing.JButton();
        btnGenerateStockReport = new javax.swing.JButton();
        lblPageName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTime = new javax.swing.JLabel();
        lblMarquee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, User!");

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnViewItemList.setText("View Item List");
        btnViewItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemListActionPerformed(evt);
            }
        });

        btnManageStockLevels.setText("Manage Stock Levels");
        btnManageStockLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStockLevelsActionPerformed(evt);
            }
        });

        btnViewPurchaseOrder.setText("View Purchase Order");
        btnViewPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPurchaseOrderActionPerformed(evt);
            }
        });

        btnGenerateStockReport.setText("Generate Stock Report");
        btnGenerateStockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateStockReportActionPerformed(evt);
            }
        });

        lblPageName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPageName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageName.setText("Inventory Manager Main Page");

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setText("Time");

        lblMarquee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMarquee.setText("Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblPageName, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnViewItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnViewPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnManageStockLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnGenerateStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblMarquee)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPageName)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblMarquee)
                .addGap(30, 30, 30)
                .addComponent(btnViewItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnViewPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnManageStockLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnGenerateStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemListActionPerformed
        IMViewItemListGUI viewItemList = new IMViewItemListGUI(this.user);
        viewItemList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewItemListActionPerformed

    private void btnViewPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPurchaseOrderActionPerformed
        IMViewPurchaseOrderGUI updateStock = new IMViewPurchaseOrderGUI(this.user);
        updateStock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewPurchaseOrderActionPerformed

    private void btnManageStockLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStockLevelsActionPerformed
        IMManageStockLevelsGUI manageStockLevels = new IMManageStockLevelsGUI(this.user);
        manageStockLevels.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageStockLevelsActionPerformed

    private void btnGenerateStockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateStockReportActionPerformed
        
        IMGenerateStockReportGUI generateStockReport = new IMGenerateStockReportGUI(this.user);
        generateStockReport.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerateStockReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to Logout?", "Confirm Logout?",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            OWSBLoginGUI loginForm = new OWSBLoginGUI();
            loginForm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateStockReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageStockLevels;
    private javax.swing.JButton btnViewItemList;
    private javax.swing.JButton btnViewPurchaseOrder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMarquee;
    private javax.swing.JLabel lblPageName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
