/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj_group33;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class SalesManagerMenuGUI extends javax.swing.JFrame {

    private User user;
    public SalesManagerMenuGUI(User user) {
        this.user = user;
        initComponents();
        lblUserid.setText("Hello, "+user.getUserId()); 
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String currentTime = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                lblTime.setText("Current Time: " + currentTime);
                }
            });
        timer.start();
        String fullText = "   Welcome to AUTOMATED PURCHASE ORDER MANAGEMENT SYSTEM      ";
        StringBuilder marqueeText = new StringBuilder(fullText);

        Timer marqueeTimer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                  
                   char first = marqueeText.charAt(0);
                   marqueeText.deleteCharAt(0).append(first);
                   lblMarquee.setText(marqueeText.toString());
               }
           });
           marqueeTimer.start();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbtnLogout = new javax.swing.JButton();
        lblUserid = new javax.swing.JLabel();
        JBtnItemManagement = new javax.swing.JButton();
        JBtnSupplierManagement = new javax.swing.JButton();
        JBtnDailySalesEntry = new javax.swing.JButton();
        JBtnPurchaseRequisition = new javax.swing.JButton();
        JBtnPurchaseOrder = new javax.swing.JButton();
        lblMarquee = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Manager Menu");

        JbtnLogout.setText("Logout");
        JbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnLogoutActionPerformed(evt);
            }
        });

        lblUserid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserid.setText("Welcome, User");

        JBtnItemManagement.setText("Item Management");
        JBtnItemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnItemManagementActionPerformed(evt);
            }
        });

        JBtnSupplierManagement.setText("Supplier Management");
        JBtnSupplierManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSupplierManagementActionPerformed(evt);
            }
        });

        JBtnDailySalesEntry.setText("Daily Sales Entry");
        JBtnDailySalesEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnDailySalesEntryActionPerformed(evt);
            }
        });

        JBtnPurchaseRequisition.setText("Purchase Requisition");
        JBtnPurchaseRequisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPurchaseRequisitionActionPerformed(evt);
            }
        });

        JBtnPurchaseOrder.setText("Purchase Order");
        JBtnPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPurchaseOrderActionPerformed(evt);
            }
        });

        lblMarquee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMarquee.setText("Title");

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUserid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JbtnLogout)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBtnPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnPurchaseRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnDailySalesEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnSupplierManagement)
                            .addComponent(JBtnItemManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 295, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTime))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblMarquee)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnLogout)
                    .addComponent(lblUserid))
                .addGap(13, 13, 13)
                .addComponent(lblMarquee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnItemManagement)
                .addGap(18, 18, 18)
                .addComponent(JBtnSupplierManagement)
                .addGap(18, 18, 18)
                .addComponent(JBtnDailySalesEntry)
                .addGap(18, 18, 18)
                .addComponent(JBtnPurchaseRequisition)
                .addGap(18, 18, 18)
                .addComponent(JBtnPurchaseOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnItemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnItemManagementActionPerformed
        SMItemManagementGUI itemForm = new SMItemManagementGUI(this.user);
        itemForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnItemManagementActionPerformed

    private void JBtnSupplierManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSupplierManagementActionPerformed
        SMSupplierManagementGUI supplierForm = new SMSupplierManagementGUI(this.user);
        supplierForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnSupplierManagementActionPerformed

    private void JBtnDailySalesEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnDailySalesEntryActionPerformed
        SMDailySalesEntryGUI salesForm = new SMDailySalesEntryGUI(this.user);
        salesForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnDailySalesEntryActionPerformed

    private void JBtnPurchaseRequisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPurchaseRequisitionActionPerformed
        SMPurchaseRequisitionGUI PRForm = new SMPurchaseRequisitionGUI(this.user);
        PRForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnPurchaseRequisitionActionPerformed

    private void JBtnPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPurchaseOrderActionPerformed
        SMPurchaseOrderGUI POForm = new SMPurchaseOrderGUI(this.user);
        POForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnPurchaseOrderActionPerformed

    private void JbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to Logout?", "Confirm Logout?",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            OWSBLoginGUI loginForm = new OWSBLoginGUI();
            loginForm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_JbtnLogoutActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnDailySalesEntry;
    private javax.swing.JButton JBtnItemManagement;
    private javax.swing.JButton JBtnPurchaseOrder;
    private javax.swing.JButton JBtnPurchaseRequisition;
    private javax.swing.JButton JBtnSupplierManagement;
    private javax.swing.JButton JbtnLogout;
    private javax.swing.JLabel lblMarquee;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserid;
    // End of variables declaration//GEN-END:variables
}
